Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MShop.Models;
using MySql.Data.MySqlClient;
using dto = MShop.Models;

namespace MShop.Controllers
{
    
    public class AboutController : Controller
    {

        public IActionResult Index()
        {

            return this.View();
        }

        public IActionResult Manuka()
        {


            return this.View();
        }
        public IActionResult ManukaOilProduction()
        {
         


            return this.View();
        }
        public IActionResult ManukaOilChemistry()
        {
         


            return this.View();
        }
        public IActionResult Arapaoa()
        {
            
            return this.View();
        }

    }
}  

Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MShop.Models;
using MySql.Data.MySqlClient;
using dto = MShop.Models;

namespace MShop.Controllers
{
    public class  ShopController : Controller
    {

        //public string culture = "en-NZ";

        //public string currency = "NZD";

        [HttpGet]
        public IActionResult Index(string ID)
        {
            string type = "";
            if (ID == null)
            {
                ID = "all";
            }
            else
            {
                type = "category";
            }
            ViewBag.Category = ID;
            ViewBag.Type = type;
            //System.Diagnostics.Debug.WriteLine("ID = " + ID);

            //if (HttpContext.Request.Query["culture"].ToString() != "") culture = HttpContext.Request.Query["culture"].ToString();

            //if (HttpContext.Request.Query["currency"].ToString() != "") currency = HttpContext.Request.Query["currency"].ToString();

            //culture = MShopClass.currencyList()[currency.ToUpper()];


            return this.View();
        }

        public ActionResult Product(string id)

        {
            ViewBag.ProductID = id;
            return this.View();
        }

        public async Task<IActionResult> Stockists()

        {
            ViewBag.Stockists = await this.GetAreas();

            return this.View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private MySqlDB MySqlDB { get; set; }
        public ShopController(MySqlDB mySqlDatabase)
        {
            this.MySqlDB = mySqlDatabase;
        }

        private async Task<List<dto.StockistModel>> GetAreas()
        {
            var ret = new List<dto.StockistModel>();

            var cmd = this.MySqlDB.Connection.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"SELECT Distinct StockistCity FROM Stockists;";

            using (var reader = await cmd.ExecuteReaderAsync())
                while (await reader.ReadAsync())
                {
                    var t = new dto.StockistModel()
                    {
                        StockistCity = reader.GetFieldValue<string>(0)

                    };

                    ret.Add(t);
                }
            return ret;
        }

       

        public IActionResult GetProductsViewComponent( string viewtype, string category)
        {
            return ViewComponent("Products", new { type = viewtype, category = category });
        }

        public IActionResult GetProductViewComponent(string id)
        {
            return ViewComponent("GetProduct", new { id = id});
        }

    }
}

Views/Shared/Components/CategoriesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MShop.Models;
using MySql.Data.MySqlClient;
using dto = MShop.Models;

namespace MShop.Views.Shared.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        private MySqlDB MySqlDB { get; set; }
        public CategoriesViewComponent(MySqlDB mySqlDatabase)
        {
            this.MySqlDB = mySqlDatabase;
        }
        private async Task<List<dto.CategoryModel>> GetCategories()
        {
            var ret = new List<dto.CategoryModel>();

            var cmd = this.MySqlDB.Connection.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"SELECT CategoryID, CategoryName, CategoryDesc, CategoryImage from ProductCategories order by categoryid asc;";

            using (var reader = await cmd.ExecuteReaderAsync())
                while (await reader.ReadAsync())
                {
                    var t = new dto.CategoryModel()
                    {
                        CategoryID = reader.GetFieldValue<int>(0),
                        CategoryName = reader.GetFieldValue<string>(1).ToUpper(),
                        CategoryDesc = reader.GetFieldValue<string>(2),
                        CategoryImage = reader.GetFieldValue<string>(3)
                    };

                    ret.Add(t);
                }
            return ret;
        }

        public async Task<IViewComponentResult> InvokeAsync(string type, string category)
        {
            //string culture = "";

            //string currency = "";

            //currency = HttpContext.Request.Query["currency"].ToString().ToUpper();

            //currency = MShopClass.getCurrency(currency);

            //culture = MShopClass.currencyList()[currency.ToUpper()];

            //ViewBag.Currency = currency;
            //ViewBag.Culture = culture;

            return View(await this.GetCategories());
        }
    }
}

Views/Shared/Components/CultureSwitcherViewComponent.cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MShop.Models;
using System.Linq;

namespace MShop.View.Shared.Component
{
    public class CultureSwitcherViewComponent : ViewComponent
    {
        private readonly IOptions<RequestLocalizationOptions> localizationOptions;
        public CultureSwitcherViewComponent(IOptions<RequestLocalizationOptions> localizationOptions) =>
            this.localizationOptions = localizationOptions;

        public IViewComponentResult Invoke()
        {
            var cultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var model = new CultureSwitcherModel
            {
                SupportedCultures = localizationOptions.Value.SupportedUICultures.ToList(),
                CurrentUICulture = cultureFeature.RequestCulture.UICulture
            };
            return View(model);
        }
    }
}

Views/Shared/Components/CurrencySwitcherViewComponent.cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MShop.Models;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;

namespace MShop.View.Shared.Component
{
    public class CurrencySwitcherViewComponent : ViewComponent
    {

        //private readonly IOptions<RequestLocalizationOptions> localizationOptions;
        //public CurrencySwitcherViewComponent(IOptions<RequestLocalizationOptions> localizationOptions) =>
        //    this.localizationOptions = localizationOptions;


        public IViewComponentResult Invoke()
        {
            
            string culture = CultureInfo.CurrentCulture.Name.ToLower();


            string currency = "";

           // currency = HttpContext.Request.Query["currency"].ToString().ToUpper();

            ViewBag.Currency = MShopClass.getCurrency(culture);
            ViewBag.Culture = culture;

            string path = HttpContext.Request.Path;

            ViewBag.CurrentURL = (path.Length > 7)? path.Substring(7):"";
            //culture = MShopClass.currencyList()[currency.ToUpper()];

            CurrencyModel currentCurrencyModel = new CurrencyModel { Currency = currency, CurrencyCulture = culture };



            var cultureSet = CultureInfo.GetCultureInfo(culture);
            Thread.CurrentThread.CurrentCulture = cultureSet;
            Thread.CurrentThread.CurrentUICulture = cultureSet;

            

            //var cultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var model = new CurrencySwitcherModel
            {
                SupportedCurrencies = MShopClass.currencyList(),
                CurrentCurrency = currentCurrencyModel

            };


         return View(model);
    }

}
}

Views/Shared/Components/GetProductViewComponent.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MShop.Models;
using MySql.Data.MySqlClient;
using dto = MShop.Models;
using MShop;
using System.Threading;

namespace MShop.Views.Shared.Components
{
    public class GetProductViewComponent : ViewComponent
    {
        private MySqlDB MySqlDB { get; set; }
        public GetProductViewComponent(MySqlDB mySqlDatabase)
        {
            this.MySqlDB = mySqlDatabase;
        }


    

        private dto.ProductModel GetProductData(string productCode)
        {
            var ret = new dto.ProductModel();

            var cmd = this.MySqlDB.Connection.CreateCommand() as MySqlCommand;
            cmd.CommandText = @"SELECT ProductId, ProductName, ProductPrice, ProductImage, ProductCode, ProductLongDesc, ProductUses, ProductIngredients, ProductPackaging FROM Products Where ProductCode='" + productCode + "';";

            using (var reader = cmd.ExecuteReader())
                while (reader.Read())
                {
                    var t = new dto.ProductModel()
                    {
                        ProductId = reader.GetFieldValue<int>(0),
                        ProductName = reader.GetFieldValue<string>(1).ToUpper(),
                        ProductPrice = reader.GetFieldValue<Single>(2),
                        ProductImage = reader.GetFieldValue<string>(3),
                        ProductCode = reader.GetFieldValue<string>(4),
                        ProductLongDesc = reader.GetFieldValue<string>(5),
                        ProductUses = reader.GetFieldValue<string>(6),
                        ProductIngredients = reader.GetFieldValue<string>(7),
                        ProductPackaging = reader.GetFieldValue<string>(8)
                    };
                    ret = t;
                }
            return ret;
        }

        public async Task<IViewComponentResult> InvokeAsync(string id)
        {
            return View(GetProductData(id));
        }
    }
}

Views/Shared/Components/ProductsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MShop.Models;
using MySql.Data.MySqlClient;
using dto = MShop.Models;
using MShop;
using System.Threading;

namespace MShop.Views.Shared.Components
{
    public class ProductsViewComponent : ViewComponent
    {
        private MySqlDB MySqlDB { get; set; }
        public ProductsViewComponent(MySqlDB mySqlDatabase)
        {
            this.MySqlDB = mySqlDatabase;
        }

        public string GetCulture = CultureInfo.CurrentCulture.Name;
        

        private async Task<List<dto.ProductModel>> GetProducts(string type, string category, string dollar)
        {
            string toCurrency = dollar;
            Single price = 0;
            float exchangeRate = 1;
            if ((toCurrency != "")&&(toCurrency.ToUpper() !="NZD")) exchangeRate = CurrencyConvertor.GetExchangeRate(toCurrency);

            if (category != null) category = category.Replace("-", " ");
            var ret = new List<dto.ProductModel>();

            var cmd = this.MySqlDB.Connection.CreateCommand() as MySqlCommand;

            string query = @"SELECT p.ProductId, p.ProductName, p.ProductPrice, p.ProductImage, p.ProductCode,  c.CategoryID, c.categoryname from products p inner join productcategories c on p.ProductCategoryID=c.categoryid ";
            
            
            if (type=="featured") query += "where productID = 15 or productID = 8 or productID = 9";
            if ((type == "category") && (category.ToLower() != "all")) query += "where categoryname = '" + category + "'";

            query += ";";
            System.Diagnostics.Debug.WriteLine("Type: " + type);
            System.Diagnostics.Debug.WriteLine("Category: " + category);
            System.Diagnostics.Debug.WriteLine("Query: " + query);
            cmd.CommandText = query;
            


            using (var reader = await cmd.ExecuteReaderAsync())
                while (await reader.ReadAsync())
                {
                    price = reader.GetFieldValue<Single>(2);
                    var t = new dto.ProductModel()
                    {
                        
                    ProductId = reader.GetFieldValue<int>(0),
                        ProductName = reader.GetFieldValue<string>(1).ToUpper(),
                        ProductPrice = price*exchangeRate,
                        ProductImage = reader.GetFieldValue<string>(3),
                        ProductCode = reader.GetFieldValue<string>(4),
                        CategoryID = reader.GetFieldValue<int>(5),
                        CategoryName = reader.GetFieldValue<string>(6)
                    };

                    ret.Add(t);
                }
            return ret;
        }

        public async Task<IViewComponentResult> InvokeAsync(string type, string category)
        {

            string culture = "";

            string currency = "";

            //currency = HttpContext.Request.Query["currency"].ToString().ToUpper();

            //currency = MShopClass.getCurrency(currency);

            //culture = MShopClass.currencyList()[currency.ToUpper()];

            //var cultureSet = CultureInfo.GetCultureInfo(culture);
            //Thread.CurrentThread.CurrentCulture = cultureSet;
            //Thread.CurrentThread.CurrentUICulture = cultureSet;

            culture = CultureInfo.CurrentCulture.Name.ToLower();

            currency = MShopClass.getCurrency(culture);

            ViewBag.Culture = CultureInfo.CurrentCulture.Name;



            //System.Diagnostics.Debug.Print("Current Culture: " + culture + ";");
            ViewBag.Dollar = currency;
            return View(await this.GetProducts(type, category, currency));
        }
    }
}

Views/Shared/Components/ShoppingCartViewComponent.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MShop.Helpers;
using MShop.Models;
using MySql.Data.MySqlClient;
using dto = MShop.Models;

namespace MShop.Views.Shared.Components
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItemModel>>(HttpContext.Session, "cart");
            if (cart == null) cart = new List<ShoppingCartItemModel>();

            string culture = CultureInfo.CurrentCulture.Name.ToLower();

            string currency = "";

            //currency = HttpContext.Request.Query["currency"].ToString().ToUpper();

            currency = MShopClass.getCurrency(culture);

            //culture = MShopClass.currencyList()[currency.ToUpper()];

           // culture = MShopClass.currencyList()[currency.ToUpper()];

            float exchangeRate = 1;
            if ((currency != "") && (currency.ToUpper() != "NZD")) exchangeRate = CurrencyConvertor.GetExchangeRate(currency);

            ViewBag.Culture = culture;
            ViewBag.Currency = currency;

            ViewBag.ExchangeRate = exchangeRate;

            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(ShoppingCartItem => ShoppingCartItem.Product.ProductPrice * ShoppingCartItem.Quantity);

            return View();
        }


    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@*@model ViewModelBase*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MShop</title>
    <link rel="icon" type="image/gif/png/jpg" href="~/images/icons/logo.jpg">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZn7BbNP3G_cBmy5cxKrs4SSAf1vMRCZQ&callback=initMap&libraries=&v=weekly"
            defer></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

    <script src="~/js/site.js"></script>
    <script src="~/js/money.js"></script>
    <script src="~/js/NumberInput.js"></script>
    <script src="~/js/Cart.js"></script>
    <script src="~/js/parallax.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="nav-content">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/logobanner.jpg" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index" ><span class="navbar-a">Home</span></a></li>
                    <li>
                        <div class="navigation">

                            <div>
                                <a class="navbar-a" asp-controller="Shop" asp-action="Index" >Shop ▾</a>
                                <br />
                                <span class="arrow"></span>
                                <div class="dropdown-content">
                                    <div style="display:inline-block;">
                                        <div class="dropdown-section" style="border-right: 2px solid #9dc46d;">
                                            <h3>Shop Online</h3>
                                            <p>
                                                Shop for our products in our online store.
                                            </p>
                                            <a asp-controller="Shop" asp-action="Index" >
                                                Shop All ▸
                                            </a>
                                        </div>
                                        <div class="dropdown-section" style="border-right: 2px solid #9dc46d;">
                                            <h3>Categories</h3>
                                            @await Component.InvokeAsync("Categories")
                                        </div>
                                        <div class="dropdown-section">
                                            <a asp-controller="Shop" asp-action="Stockists" >
                                                <h3>Stockists</h3>
                                            </a>
                                            <p>
                                                Shop for our products at your local store.
                                            </p>
                                            <a asp-controller="Shop" asp-action="Stockists" >
                                                Find a Store ▸
                                            </a>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="navigation">
                            <div>
                                <a class="navbar-a" asp-area="" asp-controller="About" asp-action="Index" >About ▾</a>
                                <br />
                                <span class="arrow"></span>
                                <div class="dropdown-content">
                                    <div style="display:inline-block;">
                                        <div class="dropdown-section" style="border-right: 2px solid #9dc46d;">
                                            <a href="/../about/">

                                                <h3>About Us</h3>
                                            </a>
                                            <p>
                                                Learn more about us.
                                            </p>
                                            <a href="/../about">
                                                <b>READ MORE ▸</b>
                                            </a>
                                        </div>
                                        <div class="dropdown-section" style="border-right: 2px solid #9dc46d;">

                                            <a href="/../about/manuka">
                                                <h3>About Manuka</h3>
                                            </a>
                                            <div class="about">
                                                <a href="/../about/manukaoilproduction">
                                                    Manuka Oil Production
                                                </a>
                                                <a href="/../about/manukaoilchemistry">
                                                    Manuka Oil Chemistry
                                                </a>

                                            </div>
                                            <a href="/../about/manuka">
                                                <b>READ MORE ▸</b>
                                            </a>
                                        </div>
                                        <div class="dropdown-section">
                                            <a href="/../about/arapaoa">
                                                <h3>Arapaoa Island</h3>
                                                <img src="~/images/ArapawaMap.gif" width="200px" />
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Search" ><span class="navbar-a">Search</span></a></li>
                </ul>
                <partial name="_LoginPartial" />
                <ul class="nav navbar-nav navbar-right">
                    <li><vc:currency-switcher /></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li>
                        <div class="navigation">
                            <div>
                                <a asp-area="" asp-controller="cart" asp-action="Index" ><span id="CartTotal" />@Context.Session.GetInt32("CartCount") Cart  ▾</a>
                                <br />
                                <span class="arrow"></span>
                                <div class="dropdown-content">
                                    <div class="CartData">
                                        @await Component.InvokeAsync("ShoppingCart")
                                    </div>
                                </div>
                            </div>
                        </div>

                    </li>
                </ul>
            </div>

        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    @RenderSection("banner", required: false)

    <div class="container body-content">
        @RenderBody()
        <hr />
        @{


        }
    </div>

    @RenderSection("widesection", required: false)

    <h1>Featured Products</h1>

    @await Component.InvokeAsync("Products", new { type = "featured" })
    <footer>
        <p>&copy; 2020 - MShop</p>
    </footer>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">356666666666++++++++699999999333333333333333333333333333369+++








































































































                66666666666666666666666666666666666666666666669
































































































































































































































































        ..-



















































































        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

    <script>
        AOS.init();
    </script>
    <script type="text/javascript">
        load_number_input();
    </script>

</body>
</html>